# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ngmcong
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Add source
      run: dotnet nuget add source --username ngmcong --password ${{ secrets.PHANTOM_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ngmcong/index.json"
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Push
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.PHANTOM_TOKEN }} --source github
      
